console.log("Number");
console.log(Number(true));
console.log(Number(1234));
console.log(Number("text"));
console.log("Boolean");
console.log(Boolean(1234));
console.log(Boolean(0));
console.log("String");
console.log(String(true));
console.log(String(1234));
console.log("parseInt");
console.log(parseInt("12,742 km：地球の直径"));
console.log("parseFloat");
console.log(parseFloat("1.618：黄金比"));
